Retail-Product-Management-v3-master/ECommercePortal/EComPortal/Models/Product/ProductItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EComPortal.Models.Product
{
    public class ProductItem
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Product Name is required.")]
        [Display(Name = "Product Name")]
        public string Name { get; set; }

        [Required]
        [Range(0, Double.PositiveInfinity)]
        public double Price { get; set; }
        public string Description { get; set; }
        public string Image_name { get; set; }

        [Range(0, 5)]
        public int Rating { get; set; }
        public bool IsAvailable { get; set; }
    }
}

Retail-Product-Management-v3-master/ECommercePortal/EComPortal/Models/Search.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EComPortal.Models
{
    public class Search
    {
        [Display(Name = "Enter Id or Name ")]
        public string str { get; set; }
    }
}

Retail-Product-Management-v3-master/ECommercePortal/EComPortal/Controllers/ProceedToBuyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using EComPortal.Models;
using EComPortal.Models.Product;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace EComPortal.Controllers
{
    public class ProceedToBuyController : Controller
    {
        readonly log4net.ILog _log4net;

        HttpClient client;
        IConfiguration configuration;
        public ProceedToBuyController(IConfiguration config)
        {
            _log4net = log4net.LogManager.GetLogger(typeof(ProceedToBuyController));

            configuration = config;
            client = new HttpClient();
            client.BaseAddress = new Uri(configuration["Authorize"]);
        }

        public ActionResult Details(string id)
        {
            _log4net.Info(" proceed to buy--get product ");

            ProductItem product = new ProductItem();

            string token = HttpContext.Request.Cookies["Token"];
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            HttpResponseMessage response;
            try
            {
                response = client.GetAsync(client.BaseAddress + "api/ProceedToBuy/" + id).Result;
            }
            catch
            {
                return RedirectToAction("Error");
            }

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                product = JsonConvert.DeserializeObject<ProductItem>(data);
                return View(product);
            }
            return RedirectToAction("Error");

        }

        public ActionResult Error()
        {
            _log4net.Info(" Error View ");

            return View();
        }
    }
}

Retail-Product-Management-v3-master/ECommercePortal/EComPortal/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using EComPortal.Models;
using EComPortal.Models.Product;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace EComPortal.Controllers
{
    public class ProductController : Controller
    {
        readonly log4net.ILog _log4net;
        HttpClient client;
        IConfiguration configuration;
        public ProductController(IConfiguration config)
        {
            _log4net = log4net.LogManager.GetLogger(typeof(ProductController));
            configuration = config;
            client = new HttpClient();
            client.BaseAddress = new Uri(configuration["Authorize"]);
        }

        public IActionResult Index()
        {
            _log4net.Info(" Index--Get All ");
            List<ProductItem> ls = new List<ProductItem>();

            string token = HttpContext.Request.Cookies["Token"];
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            HttpResponseMessage response;
            try
            {
                _log4net.Info(" Http GET request--Get All ");
                response = client.GetAsync(client.BaseAddress + "api/product").Result;
            }
            catch
            {
                return RedirectToAction("Error");
            }

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                ls = JsonConvert.DeserializeObject<List<ProductItem>>(data);
                return View(ls);
            }
            return RedirectToAction("Error");
        }
        public ActionResult Search()
        {
            _log4net.Info(" Search Action called ");
            return View();
        }
        [HttpPost]
        public ActionResult Search(Search obj)
        {
            return RedirectToAction("Details", new { id = obj.str });
        }
        public ActionResult Details(string id)
        {
            _log4net.Info(" Get detail by id -- "+id);

            ProductItem product = new ProductItem();

            string token = HttpContext.Request.Cookies["Token"];
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            HttpResponseMessage response;
            try
            {
                response = client.GetAsync(client.BaseAddress + "api/product/" + id).Result;
            }
            catch
            {
                return RedirectToAction("Error");
            }

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                product = JsonConvert.DeserializeObject<ProductItem>(data);
                return View(product);
            }
            ViewBag.Error = "Product not found!";
            return View("Search");

        }



        public ActionResult Edit(int id)
        {
            _log4net.Info(" Edit detail by id -- " + id);

            ProductItem product = new ProductItem();

            string token = HttpContext.Request.Cookies["Token"];
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            HttpResponseMessage response;
            try
            {
                response = client.GetAsync(client.BaseAddress + "api/product/" + id).Result;
            }
            catch
            {
                return RedirectToAction("Error");
            }

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                product = JsonConvert.DeserializeObject<ProductItem>(data);
                return View(product);
            }
            return RedirectToAction("Error");
        }
        [HttpPost]
        public ActionResult Edit(ProductItem product)
        {
            _log4net.Info(" Post detail Action ");

            string token = HttpContext.Request.Cookies["Token"];
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            string data = JsonConvert.SerializeObject(product);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");

            HttpResponseMessage response;
            try
            {
                response = client.PutAsync(client.BaseAddress + "api/product/"+ product.Id, content).Result;
            }
            catch
            {
                return RedirectToAction("Error");
            }
            if (response.IsSuccessStatusCode)
                return RedirectToAction("Index");
            return RedirectToAction("Error");
        }
        public ActionResult Error()
        {
            _log4net.Info(" Error View ");

            return View();
        }
    }
}

Retail-Product-Management-v3-master/ECommercePortal/EComPortal/Controllers/WishlistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using EComPortal.Models;
using EComPortal.Models.Product;
using EComPortal.Models.Wishlist;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace EComPortal.Controllers
{
    public class WishlistController : Controller
    {
        readonly log4net.ILog _log4net;

        private readonly ApplicationDbContext _db;

        HttpClient client;
        IConfiguration configuration;
        public WishlistController(IConfiguration config, ApplicationDbContext db)
        {
            _log4net = log4net.LogManager.GetLogger(typeof(WishlistController));

            _db = db;
            configuration = config;
            client = new HttpClient();
            client.BaseAddress = new Uri(configuration["Authorize"]);
        }
       
        public IActionResult Index()
        {
            _log4net.Info(" Index--Get All ");

            string user = HttpContext.Request.Cookies["UserId"];
            List<WishlistItem> items = new List<WishlistItem>();
            items = _db.WishlistItems.ToList();

            List<WishlistItem> listUser = new List<WishlistItem>();
            foreach (WishlistItem w in items)
            {
                if (w.UserName == user)
                {
                    listUser.Add(w);
                }
            }           
            return View(listUser);
        }

        public IActionResult Delete(int id)
        {
            _log4net.Info(" Delete--id-- " + id);

            WishlistItem item = new WishlistItem();
            item =_db.WishlistItems.FirstOrDefault(x => x.Id == id);
            _db.WishlistItems.Remove(item);
            _db.SaveChanges();

            return RedirectToAction("index");
        }

        public IActionResult AddItem(string id)
        {
            _log4net.Info(" Add item to Wishlist ");

            ProductItem product = new ProductItem();

            string token = HttpContext.Request.Cookies["Token"];
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            HttpResponseMessage response;
            
            response = client.GetAsync(client.BaseAddress + "api/product/" + id).Result;

            string data = response.Content.ReadAsStringAsync().Result;
            product = JsonConvert.DeserializeObject<ProductItem>(data);

            WishlistItem item = new WishlistItem();
            item.UserName = HttpContext.Request.Cookies["UserId"];
            item.ProductName = product.Name;
            item.ProductId = product.Id;
            item.Price = product.Price;
            item.Description = product.Description;

            _db.WishlistItems.Add(item);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }
        
    }
}

Retail-Product-Management-v3-master/ECommercePortal/EComPortal/Views/Product/Details.cshtml
@model EComPortal.Models.Product.ProductItem

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ProductItem</h4>
    <hr />
    @if (!string.IsNullOrEmpty(ViewBag.Error))
    {
        <div class="alert alert-danger">@ViewBag.Error</div>
    }
    <dl class="row">
        <dt class="col-sm-2" hidden>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10" hidden>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2" hidden>
            @Html.DisplayNameFor(model => model.Image_name)
        </dt>
        <dd class="col-sm-10" hidden>
            @Html.DisplayFor(model => model.Image_name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10" hidden>
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class="col-sm-2" hidden>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>
    </dl>
</div>
<div>
    <a style="margin-bottom:5px" class="btn btn-success" asp-controller="ProceedToBuy" asp-action="Details" asp-route-id="@Model.Id.ToString()">Proceed To Buy</a>
    <a style="margin-bottom:5px" class="btn btn-primary" asp-area="" asp-controller="Wishlist" asp-action="AddItem" asp-route-id="@Model.Id.ToString()">Add To Wishlist</a>
    <a style="margin-bottom:5px" class="btn btn-info" asp-action="Index">Back to List</a>
</div>

Retail-Product-Management-v3-master/ECommercePortal/EComPortal/Views/Product/Edit.cshtml
@model EComPortal.Models.Product.ProductItem

@{
    ViewData["Title"] = "Edit";
}

<h1>Give Rating</h1>

<h4>ProductItem</h4>
<hr />
<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>
</dl>
<div class="row">
    <div class="col-md-4">

        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group" hidden>
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                @Html.DropDownListFor(m => m.Rating, Enumerable.Range(1, 5).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }))
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Rate" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<br />
<div>
    <a asp-action="Index"class="btn badge-info">Back to List</a>
</div>

Retail-Product-Management-v3-master/ECommercePortal/EComPortal/Views/Product/Index.cshtml
@model IEnumerable<EComPortal.Models.Product.ProductItem>

@{
    ViewData["Title"] = "Index";
}

<h1>All Products Here</h1>
<div class="container row p-0 m-0">
    <div class = "col-9"><a asp-action="Index">Refresh</a></div>
    
    <div class = "col-3 "><a asp-controller="Product" asp-action="Search" class="btn btn-primary">Search Product Here</a></div>
</div>
<br />
<table class="table">
    <thead>
        <tr>
            <th hidden>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.Image_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.IsAvailable)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td hidden>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td hidden>
                @Html.DisplayFor(modelItem => item.Image_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td hidden>
                @Html.DisplayFor(modelItem => item.IsAvailable)
            </td>
            <td>
                <a class="btn btn-outline-info" asp-area="" asp-controller="Product" asp-action="Edit" asp-route-id="@item.Id">Rate</a>
                <a class="btn btn-outline-success" asp-area="" asp-controller="Wishlist" asp-action="AddItem" asp-route-id="@item.Id.ToString()">Add To WishList</a>
                <a class="btn btn-success" asp-area="" asp-controller="ProceedToBuy" asp-action="Details" asp-route-id="@item.Id.ToString()">Proceed To Buy</a>
            </td>
        </tr>
}
    </tbody>
</table>

Retail-Product-Management-v3-master/ECommercePortal/EComPortal/Views/Product/Search.cshtml
@model EComPortal.Models.Search

@{
    ViewData["Title"] = "Search";
}

<h1>Search</h1>

<h4>Search</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Search">

            @if (!string.IsNullOrEmpty(ViewBag.Error))
            {
                <div class="alert alert-danger">@ViewBag.Error</div>
            }

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="str" class="control-label"></label>
                <input asp-for="str" class="form-control" />
                <span asp-validation-for="str" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>